#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
prepare_service single
SERVICE_NAME="secrets"

if var_true "${CONTAINER_ENABLE_SECRETS}" ; then
    call nfra_parse_secrets
else
    service_stop "$(basename "$0")"
fi

liftoff
output_on
