#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
prepare_service single
SERVICE_NAME="metrics"

if var_true "${CONTAINER_ENABLE_METRICS}" ; then
    :
else
    :
fi

liftoff
output_on