#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
prepare_service single
SERVICE_NAME="monitoring"

    if var_true "${CONTAINER_ENABLE_MONITORING}" ; then
        if ! binary_exists $(var_value ${CONTAINER_MONITORING_BACKEND^^}_BINARY); then
            print_debug "Disabling Monitoring Backend ${CONTAINER_MONITORING_BACKEND} - Binary '$(echo ${CONTAINER_MONITORING_BACKEND^^}_BINARY)' not found"
            service_stop "$(basename "$0")"
        else
            call nfra_configure_monitoring_${CONTAINER_MONITORING_BACKEND,,}_init
        fi
    else
        service_stop "$(basename "$0")"
    fi

liftoff
output_on