#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="monitoring"
output_off
prepare_service single
check_container_initialized
check_service_initialized init
liftoff

call nfra_configure_monitoring_${CONTAINER_MONITORING_BACKEND,,}_run
