#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init

print_debug "Commencing container shutdown sequence"

if [ -n "${CONTAINER_SHUTDOWN_PRE_COMMAND}" ]; then
    if [ -f "${CONTAINER_SHUTDOWN_PRE_COMMAND}" ] && [ ! -x "${CONTAINER_SHUTDOWN_PRE_COMMAND}" ]; then
        chmod +x "${CONTAINER_SHUTDOWN_PRE_COMMAND}"
    fi
    print_debug "Executing pre shutdown command '${CONTAINER_SHUTDOWN_PRE_COMMAND}'"
    eval "${CONTAINER_SHUTDOWN_PRE_COMMAND}"
fi

for fullpath_basefinish in /container/base/finish/finish.d/* ; do
    if [ -x "${fullpath_basefinish}" ] && [ ! -d "${fullpath_basefinish}" ] ; then
        basefinish=$(basename $fullpath_basefinish)
        command_name=$(echo "${basefinish}" | sed -E 's/^[0-9]+-//' | tr ' -' '__')
        if [ "${basefinish}" != "zzz-container" ] ; then
            pre_command="CONTAINER_SHUTDOWN_PRE_COMMAND_${command_name}"
            if [ -n "${!pre_command}" ]; then
                if [ -f "${!pre_command}" ] && [ ! -x "${!pre_command}" ]; then
                    chmod +x "${!pre_command}"
                fi
                print_debug "Executing command from ${pre_command}"
                eval "${!pre_command}"
            fi
            if [ -f /override/base/finish/pre/${basefinish} ] && [ -x /override/base/finish/pre/${basefinish} ] ; then
                /override/base/finish/pre/${basefinish}
            elif [ -f /container/base/finish/pre/${basefinish} ] && [ -x /container/base/finish/pre/${basefinish} ] ; then
                /container/base/finish/pre/${basefinish}
            fi
            if [ -f /override/base/finish/init.d/${basefinish} ] && [ -x /override/base/finish/init.d/${basefinish} ] ; then
                /override/base/finish/init.d/"${basefinish}"
            else
                "${fullpath_basefinish}"
            fi
            post_command="CONTAINER_SHUTDOWN_POST_COMMAND_${command_name}"
            if [ -n "${!post_command}" ]; then
                if [ -f "${!post_command}" ] && [ ! -x "${!post_command}" ]; then
                    chmod +x "${!post_command}"
                fi
                print_debug "Executing command from ${post_command}"
                eval "${!post_command}"
            fi
            if [ -f /override/base/inint/post/${basefinish} ] && [ -x /override/base/finish/post/${basefinish} ] ; then
                /override/base/finish/post/${basefinish}
            elif [ -f /container/base/finish/post/${basefinish} ] && [ -x /container/base/finish/post/${basefinish} ] ; then
                /container/base/finish/post/${basefinish}
            fi
        fi
    fi
done

for fullpath_contfinish in /container/finish/finish.d/* ; do
    if [ -x "${fullpath_contfinish}" ] && [ ! -d "${fullpath_contfinish}" ] ; then
        contfinish=$(basename $fullpath_contfinish)
        command_name=$(echo "${contfinish}" | sed -E 's/^[0-9]+-//' | tr ' -' '__')
        pre_command="CONTAINER_SHUTDOWN_PRE_COMMAND_${command_name}"
            if [ -n "${!pre_command}" ]; then
                if [ -f "${!pre_command}" ] && [ ! -x "${!pre_command}" ]; then
                    chmod +x "${!pre_command}"
                fi
                print_debug "Executing command from ${pre_command}"
                eval "${!pre_command}"
            fi
        if [ -f /override/finish/pre/${contfinish} ] && [ -x /override/finish/pre/${contfinish} ] ; then
            /override/finish/pre/${contfinish}
        elif [ -f /container/finish/pre/${contfinish} ] && [ -x /container/finish/pre/${contfinish} ] ; then
            /container/finish/pre/${contfinish}
        fi
        if [ -f /override/finish/init.d/${contfinish} ] && [ -x /override/finish/init.d/${contfinish} ] ; then
            /override/finish/init.d/"${contfinish}"
        else
            "${fullpath_contfinish}"
        fi
        post_command="CONTAINER_SHUTDOWN_POST_COMMAND_${command_name}"
        if [ -n "${!post_command}" ]; then
            if [ -f "${!post_command}" ] && [ ! -x "${!post_command}" ]; then
                chmod +x "${!post_command}"
            fi
            print_debug "Executing command from ${post_command}"
            eval "${!post_command}"
        fi
        if [ -f /override/inint/post/${contfinish} ] && [ -x /override/finish/post/${contfinish} ] ; then
            /override/finish/post/${contfinish}
        elif [ -f /container/finish/post/${contfinish} ] && [ -x /container/finish/post/${contfinish} ] ; then
            /container/finish/post/${contfinish}
        fi
    fi
done

if [ -n "${CONTAINER_SHUTDOWN_POST_COMMAND}" ]; then
    if [ -f "${CONTAINER_SHUTDOWN_POST_COMMAND}" ] && [ ! -x "${CONTAINER_SHUTDOWN_POST_COMMAND}" ]; then
        chmod +x "${CONTAINER_SHUTDOWN_POST_COMMAND}"
    fi
    print_debug "Executing post shutdown command '${CONTAINER_SHUTDOWN_POST_COMMAND}'"
    eval "${CONTAINER_SHUTDOWN_POST_COMMAND}"
fi
