#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

chmod -f -R 0755 \
                    /{container,override}/{available,init.d,finish}/{available,post,pre} \
                > /dev/null 2>&1

#if [ -n "$(ls -A "/container/state" 2>/dev/null)" ] ; then
if [ -d /contaner/state ]; then
    echo "Detected Container that has been restarted - Cleaning '/container/state' files"
    mv /container/state/startup /tmp/
    rm -rf /container/state/*
    rm -rf /etc/services.d/*
    mv /tmp/startup /container/state/
    echo "$(date +%s) $(date +'%Y-%m-%d %H:%M:%S %Z') - Warm restart detected" >> /container/state/restart
else
    mkdir -p /container/state
    echo "$(date +%s) $(date +'%Y-%m-%d %H:%M:%S %Z') - Container started" >> /container/state/startup
fi

mkdir -p /container/state/{init,run}
source /container/base/functions/container/init

if [ -n "${CONTAINER_INIT_PRE_COMMAND}" ]; then
    if [ -f "${CONTAINER_INIT_PRE_COMMAND}" ] && [ ! -x "${CONTAINER_INIT_PRE_COMMAND}" ]; then
        chmod +x "${CONTAINER_INIT_PRE_COMMAND}"
    fi
    print_debug "Executing pre init command '${CONTAINER_INIT_PRE_COMMAND}'"
    eval "${CONTAINER_INIT_PRE_COMMAND}"
fi

for fullpath_baseinit in /container/base/init/init.d/* ; do
    if [ -x "${fullpath_baseinit}" ] && [ ! -d "${fullpath_baseinit}" ] ; then
        baseinit=$(basename $fullpath_baseinit)
        command_name=$(echo "${baseinit}" | sed -E 's/^[0-9]+-//' | tr ' -' '__')
        if [ "${baseinit}" != "zzz-container" ] ; then
            pre_command="CONTAINER_INIT_PRE_COMMAND_${command_name}"
            if [ -n "${!pre_command}" ]; then
                if [ -f "${!pre_command}" ] && [ ! -x "${!pre_command}" ]; then
                    chmod +x "${!pre_command}"
                fi
                print_debug "Executing command from ${pre_command}"
                eval "${!pre_command}"
            fi
            if [ -f /override/base/init/pre/"${baseinit}" ] && [ -x /override/base/init/pre/"${baseinit}" ] ; then
                /override/base/init/pre/"${baseinit}"
            elif [ -f /container/base/init/pre/"${baseinit}" ] && [ -x /container/base/init/pre/"${baseinit}" ] ; then
                /container/base/init/pre/"${baseinit}"
            fi
            if [ -f /override/base/init/init.d/"${baseinit}" ] && [ -x /override/base/init/init.d/"${baseinit}" ] ; then
                /override/base/init/init.d/"${baseinit}"
            else
                if [ -f "${fullpath_baseinit}" ]; then "${fullpath_baseinit}" ; fi
            fi
            post_command="CONTAINER_INIT_POST_COMMAND_${command_name}"
            if [ -n "${!post_command}" ]; then
                if [ -f "${!post_command}" ] && [ ! -x "${!post_command}" ]; then
                    chmod +x "${!post_command}"
                fi
                print_debug "Executing command from ${post_command}"
                eval "${!post_command}"
            fi
            if [ -f /override/base/init/post/"${baseinit}" ] && [ -x /override/base/init/post/"${baseinit}" ] ; then
                /override/base/init/post/"${baseinit}"
            elif [ -f /container/base/init/post/"${baseinit}" ] && [ -x /container/base/init/post/"${baseinit}" ] ; then
                /container/base/init/post/"${baseinit}"
            fi
        fi
    fi
done

for fullpath_continit in /container/init/init.d/* ; do
    if [ -x "${fullpath_continit}" ] && [ ! -d "${fullpath_continit}" ] ; then
        continit=$(basename $fullpath_continit)
        command_name=$(echo "${continit}" | sed -E 's/^[0-9]+-//' | tr ' -' '__')
        pre_command="CONTAINER_INIT_PRE_COMMAND_${command_name}"
        if [ -n "${!pre_command}" ]; then
            if [ -f "${!pre_command}" ] && [ ! -x "${!pre_command}" ]; then
                chmod +x "${!pre_command}"
            fi
            print_debug "Executing command from ${pre_command}"
            eval "${!pre_command}"
        fi
        if [ -f /override/init/pre/"${continit}" ] && [ -x /override/init/pre/"${continit}" ] ; then
            /override/init/pre/"${continit}"
        elif [ -f /container/init/pre/"${continit}" ] && [ -x /container/init/pre/"${continit}" ] ; then
            /container/init/pre/"${continit}"
        fi
        if [ -f /override/init/init.d/"${continit}" ] && [ -x /override/init/init.d/"${continit}" ] ; then
            /override/init/init.d/"${continit}"
        else
            if [ -f "${fullpath_continit}" ]; then "${fullpath_continit}" ; fi
        fi
        post_command="CONTAINER_INIT_POST_COMMAND_${command_name}"
        if [ -n "${!post_command}" ]; then
            if [ -f "${!post_command}" ] && [ ! -x "${!post_command}" ]; then
                chmod +x "${!post_command}"
            fi
            print_debug "Executing command from ${post_command}"
            eval "${!post_command}"
        fi
        if [ -f /override/init/post/"${continit}" ] && [ -x /override/init/post/"${continit}" ] ; then
            /override/init/post/"${continit}"
        elif [ -f /container/init/post/"${continit}" ] && [ -x /container/init/post/"${continit}" ] ; then
            /container/init/post/"${continit}"
        fi
    fi
done

if [ -f "/override/base/init/init.d/zzz-container" ] ; then
    /override/base/init/init.d/zzz-container
elif [ -f "/container/base/init/init.d/zzz-container" ] ; then
    /container/base/init/init.d/zzz-container
fi
