name: debian

on:
  workflow_call

jobs:
  build_debian:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        distro_variant: [ "trixie", "bookworm" ]
        image_variant:
          - core
          - faflopza
          - faflopzaze
    env:
      DISTRO: "debian"
      DISTRO_VARIANT: ${{ matrix.distro_variant }}
      IMAGE_VARIANT: ${{ matrix.image_variant }}
      ARCH: "linux/amd64,linux/arm64"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Encrypted Files
        uses: actions/download-artifact@v4
        with:
          name: encrypted-artifacts
          path: ./
      - name: Set Modules
        id: set_modules
        run: |
          case "${IMAGE_VARIANT}" in
              "core" )
                  echo "IMAGE_BASE_MODULES=+age,+cron,+logrotate,+s6overlay,+msmtp" >> $GITHUB_ENV
              ;;
              "faflopza" )
                  echo "IMAGE_BASE_MODULES=+age,+cron,+logrotate,+s6overlay,+msmtp" >> $GITHUB_ENV
                  echo "IMAGE_MODULES=+fail2ban,+fluentbit,+openbao,+zabbix" >> $GITHUB_ENV
              ;;
              "faflopzaze" )
                  echo "IMAGE_BASE_MODULES=+age,+cron,+logrotate,+s6overlay,+msmtp" >> $GITHUB_ENV
                  echo "IMAGE_MODULES=+fail2ban,+fluentbit,+openbao,+zabbix,+zerotier" >> $GITHUB_ENV
              ;;
          esac
      - name: Build Image
        uses: nfrastack/gha/.github/actions/build_base_image@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
