name: alpine

on:
  workflow_call

jobs:
  build_alpine:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        build:
          - { distro: "alpine", distro_variant: "3.22", latest: "true", distro_latest: "true", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.19", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.16", latest: "false", distro_latest: "false", arch: "linux/amd64",linux/arm64" }
          - { distro: "alpine", distro_variant: "3.15", latest: "false", distro_latest: "false", arch: "linux/amd64",linux/arm64" }
          - { distro: "alpine", distro_variant: "3.12", latest: "false", distro_latest: "false", arch: "linux/amd64",linux/arm64" }
          - { distro: "debian", distro_variant: "trixie", latest: "false", distro_latest: "true", arch: "linux/amd64,linux/arm64" }
          - { distro: "debian", distro_variant: "bookworm", latest: "false", distro_latest: "true", arch: "linux/amd64,linux/arm64" }
        image_variant:
          - core
          - faflopza
          - faflopzaze
    env:
      DISTRO: ${{ matrix.build.distro }}
      DISTRO_VARIANT: ${{ matrix.build.distro_variant }}
      LATEST: ${{ matrix.build.latest || 'true' }}
      DISTRO_LATEST: ${{ matrix.build.distro_latest || 'false' }}
      IMAGE_VARIANT: ${{ matrix.image_variant }}
      ARCH: ${{ matrix.build.arch || 'linux/amd64,linux/arm64' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Download Encrypted Files
        uses: actions/download-artifact@v4
        with:
          name: encrypted-artifacts
          path: ./
      - name: Set Modules
        id: set_modules
        run: |
          case "${IMAGE_VARIANT}" in
              "core" )
                  echo "IMAGE_BASE_MODULES=+age,+cron,+logrotate,+s6overlay,+msmtp," >> $GITHUB_ENV
              ;;
              "faflopza" )
                  echo "IMAGE_BASE_MODULES=+age,+cron,+logrotate,+s6overlay,+msmtp," >> $GITHUB_ENV
                  echo "IMAGE_MODULES=+fail2ban,+fluentbit,+openbao,+zabbix" >> $GITHUB_ENV
              ;;
              "faflopzaze" )
                  echo "IMAGE_BASE_MODULES=+age,+cron,+logrotate,+s6overlay,+msmtp," >> $GITHUB_ENV
                  echo "IMAGE_MODULES=+fail2ban,+fluentbit,+openbao,+zabbix,+zerotier" >> $GITHUB_ENV
              ;;
          esac
      - name: Build Image
        uses: nfrastack/gha/.github/actions/build_base_image@main
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
